FROM golang:1.22.3-alpine3.20 AS builder

WORKDIR /app
COPY . .

RUN go build -ldflags="-w -s" -o orchestrator cmd/orchestrator/main.go

# ----------------------------

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /app/orchestrator .
COPY --from=builder /app/.env.docker .env

ENTRYPOINT [ "./orchestrator" ]
