FROM golang:1.22.3-alpine3.20 AS builder

WORKDIR /app
COPY . .

RUN go build -ldflags="-w -s" -o input cmd/input/main.go

# ----------------------------

FROM alpine:3.20

WORKDIR /app
COPY --from=builder /app/input .
COPY --from=builder /app/.env.docker .env

ENTRYPOINT [ "./input" ]
